remote_theme: pages-themes/midnight@v0.2.0
title: "Terrap Docs"
description: "The Official Terrap Docs"
plugins:
  - jekyll-remote-theme
source: "/"
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: docs.sirrend.com
url: https://docs.sirrend.com